#!/bin/sh

set -e

echo "🚀 UrGood CI Post-Clone Script"
echo "=============================="

# Print environment info
echo "📱 Xcode version: $(xcodebuild -version)"
echo "🍎 macOS version: $(sw_vers -productVersion)"
echo "📂 Working directory: $(pwd)"

# Check if we're running in Xcode Cloud
if [ "$CI_XCODE_CLOUD" = "TRUE" ]; then
    echo "✅ Running in Xcode Cloud"
else
    echo "⚠️  Not running in Xcode Cloud (local test)"
fi

# Install dependencies
echo ""
echo "📦 Installing dependencies..."

# Swift Package Manager dependencies are automatically resolved by Xcode Cloud
echo "✅ Swift Package Manager dependencies will be resolved automatically"

# If you were using CocoaPods, you would uncomment this:
# if [ -f "Podfile" ]; then
#     echo "Installing CocoaPods..."
#     bundle install
#     bundle exec pod install
# fi

# Set up environment variables from Xcode Cloud secrets
echo ""
echo "🔐 Setting up environment variables..."

# Create the urgood directory if it doesn't exist (for Secrets.xcconfig)
mkdir -p urgood

# Create Secrets.xcconfig from Xcode Cloud environment variables
cat > urgood/Secrets.xcconfig << EOF
// Auto-generated by Xcode Cloud CI
// Do not commit this file

OPENAI_API_KEY = \${OPENAI_API_KEY}
ELEVENLABS_API_KEY = \${ELEVENLABS_API_KEY}
FIREBASE_CONFIG = \${FIREBASE_CONFIG}
REVENUECAT_API_KEY = \${REVENUECAT_API_KEY}
EOF

echo "✅ Created Secrets.xcconfig"

# Verify critical files exist
echo ""
echo "🔍 Verifying project structure..."

if [ ! -f "urgood/urgood.xcodeproj/project.pbxproj" ]; then
    echo "❌ ERROR: Xcode project not found!"
    exit 1
fi

if [ ! -f "urgood/urgood/urgoodApp.swift" ]; then
    echo "❌ ERROR: Main app file not found!"
    exit 1
fi

echo "✅ Project structure verified"

# Check for GoogleService-Info.plist
echo ""
echo "🔍 Checking Firebase configuration..."

if [ ! -f "urgood/urgood/GoogleService-Info.plist" ]; then
    echo "⚠️  WARNING: GoogleService-Info.plist not found"
    echo "   This may cause Firebase-related features to fail"
else
    echo "✅ Firebase configuration found"
fi

# Print available schemes
echo ""
echo "📋 Available schemes:"
xcodebuild -list -project urgood/urgood.xcodeproj

echo ""
echo "✅ Post-clone setup complete!"
echo "=============================="

