import Foundation

struct TermsOfService {
    static let content = """
# TERMS OF SERVICE

**Effective Date:** October 20, 2025
**Last Updated:** October 20, 2025

## 1. ACCEPTANCE OF TERMS

By downloading, installing, or using UrGood ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.

These Terms are entered into by and between you and UrGood, Inc. ("UrGood," "we," "us," or "our"), located at 123 Mental Health St, San Francisco, CA 94105, United States. You can contact us at legal@urgood.app or support@urgood.app.

## 2. DESCRIPTION OF SERVICE

UrGood is a wellness and habit-tracking application designed to provide emotional support and personal development tools. **UrGood is NOT therapy, medical treatment, or professional mental health care.** UrGood does not replace licensed mental health providers, medical professionals, or emergency services.

### What UrGood Provides:
- Emotional check-ins and mood tracking
- AI-powered conversational support
- Habit tracking and personal insights
- Wellness resources and educational content curated for general wellness

### What UrGood Does NOT Provide:
- Medical advice, diagnosis, or treatment
- Professional therapy or counseling
- Crisis intervention services
- Emergency mental health support

## 3. AGE REQUIREMENTS

**You must be 16 years or older to use UrGood.** This app is designed for teens and adults. By using the App, you represent and warrant that you are at least 16 years of age.

## 4. EMERGENCY DISCLAIMER

**IMPORTANT:** If you are experiencing a mental health crisis or having thoughts of self-harm or suicide, DO NOT rely on UrGood for help. Instead:

- **US:** Call 988 (Suicide & Crisis Lifeline)
- **Emergency:** Call 911 or your local emergency services
- **Crisis Text:** Text HOME to 741741
- **International:** Visit findahelpline.com

UrGood is not equipped to handle emergencies and should never be used as a substitute for professional crisis intervention.

## 5. USER RESPONSIBILITIES

### You agree to:
- Provide accurate information during registration
- Use the App only for lawful purposes
- Not share your account credentials
- Not attempt to reverse engineer or hack the App
- Respect the intended use of wellness and personal development

### You agree NOT to:
- Use the App if you are under 16 years old
- Rely on the App for medical or mental health treatment
- Share harmful, illegal, or inappropriate content
- Attempt to circumvent security measures
- Use the App during mental health emergencies

## 6. PRIVACY AND DATA

Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information. Key points:
- **Local Storage:** Your data stays on your device by default
- **No Data Selling:** We never sell your personal information
- **Minimal Collection:** We only collect information necessary for the App to function
- **Encryption:** All data is encrypted in transit and at rest
- **Full Policy:** https://urgood.app/privacy

## 7. INTELLECTUAL PROPERTY

The App and its content are owned by UrGood and protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, or distribute the App without permission.

## 8. DISCLAIMERS AND LIMITATIONS

### Medical Disclaimer
UrGood is not a medical device and is not intended to diagnose, treat, cure, or prevent any disease or medical condition. Always consult qualified healthcare professionals for medical advice.

### AI Limitations
The AI responses in UrGood are generated by artificial intelligence and may not always be accurate, appropriate, or helpful. Do not rely solely on AI responses for important decisions. You remain responsible for your actions and decisions.

### No Warranties
The App is provided "as is" without warranties of any kind. We do not guarantee that the App will be error-free or continuously available.

## 9. LIMITATION OF LIABILITY

To the maximum extent permitted by law, UrGood shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages arising from or related to your use of the App, even if we have been advised of the possibility of such damages. Our total aggregate liability for any claim arising from the App shall not exceed the amount you paid (if any) for access to the App in the twelve (12) months preceding the claim.

## 10. SUBSCRIPTION AND BILLING

### Premium Features
Some features require a paid subscription. Subscription terms:
- Billing occurs through your App Store account
- Subscriptions auto-renew unless cancelled
- Refunds are subject to App Store policies
- Premium features may change over time

### Free Features
Basic wellness features remain free and accessible to all users.

## 11. TERMINATION

We may terminate or suspend your access to the App if you violate these Terms, engage in fraudulent or illegal activities, or cause harm to other users or to UrGood. You may stop using the App at any time by deleting it from your device. Upon termination, these Terms will continue to apply to any outstanding obligations or liabilities incurred prior to termination.

## 12. CHANGES TO TERMS

We may update these Terms periodically. Continued use of the App after changes constitutes acceptance of the new Terms.

## 13. GOVERNING LAW

These Terms and any disputes arising out of or relating to them are governed by the laws of the State of California, United States, without regard to conflict of law principles. All disputes must be resolved in the state or federal courts located in San Francisco County, California, and you consent to the personal jurisdiction of those courts.

## 14. CONTACT INFORMATION

For questions about these Terms, contact us at:
- Email: legal@urgood.app
- Support: support@urgood.app
- Website: https://urgood.app/legal
- Mail: UrGood, Inc., 123 Mental Health St, San Francisco, CA 94105, United States

For immediate assistance with the App (non-legal matters), email support@urgood.app.

---

**Remember:** UrGood is a wellness tool, not medical treatment. For mental health emergencies, always contact professional crisis services or emergency responders.
"""
}
